version: "3.7"
services:
  app:
    build:
      args:
        user: marcrine
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: atk
    container_name: atk-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - atk
  db:
    image: mysql:8.0
    container_name: atk-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: atk
      MYSQL_ROOT_PASSWORD: marcrine
      MYSQL_PASSWORD: marcrine
      MYSQL_USER: atk_user
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - atk
  nginx:
    image: nginx:alpine
    container_name: atk-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - atk
networks:
  atk:
    driver: bridge
